# PROD表
CREATE TABLE IF NOT EXISTS `PROD`(
	`ID` INT AUTO_INCREMENT,
	`ASIN` VARCHAR(15),
	`TITLE` TEXT,
	`PRICE` REAL,
	`RATING` REAL,
	`COUNTRY` VARCHAR(50),
	PRIMARY KEY (`ID`),
	CONSTRAINT `ID_AC` UNIQUE (`ASIN`,`COUNTRY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# KWORD表
CREATE TABLE IF NOT EXISTS `KWORD`(
	`ID` INT AUTO_INCREMENT,
	`KEYWORD` VARCHAR(50) UNIQUE,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# PROD_KWORD表
CREATE TABLE IF NOT EXISTS `PROD_KWORD`(
	`ID` INT AUTO_INCREMENT,
	`PROD_ID` INT, 
	`KWORD_ID` INT,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`PROD_ID`) REFERENCES `PROD`(`ID`),
	FOREIGN KEY(`KWORD_ID`) REFERENCES `KWORD`(`ID`),
	CONSTRAINT `ID_PK` UNIQUE (`PROD_ID`,`KWORD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
# PROD_KWORD_RANK表
CREATE TABLE IF NOT EXISTS `PROD_KWORD_RANK`(
	`ID` INT AUTO_INCREMENT,
	`PK_ID` INT, 
	`QID` INT, 
	`RANK` INT, 
	`URL` TEXT, 
	`IP` VARCHAR(25), 
	`HEADERS` TEXT,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`PK_ID`) REFERENCES `PROD_KWORD`(`ID`),
	CONSTRAINT `ID_PKQ` UNIQUE (`PK_ID`,`QID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# STORE表
CREATE TABLE IF NOT EXISTS `STORE`(
	`ID` INT AUTO_INCREMENT,
	`MARKET` VARCHAR(20),
	`MERCHANT` VARCHAR(20),
	`NAME` VARCHAR(50),
	PRIMARY KEY (`ID`),
	CONSTRAINT `ID_MM` UNIQUE (`MARKET`,`MERCHANT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# STORE_PROD表
CREATE TABLE IF NOT EXISTS `STORE_PROD`(
	`STORE_ID` INT, 
	`PROD_ID` INT,
	FOREIGN KEY (`STORE_ID`) REFERENCES `STORE`(`ID`),
	FOREIGN KEY (`PROD_ID`) REFERENCES `PROD`(`ID`),
	CONSTRAINT `ID_SP` UNIQUE (`STORE_ID`,`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
